#
# Copyright 2023 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[versions]

compileSdk = '33'
targetSdk = '33'
agp = '7.4.0'

# AndroidX
activity = '1.7.0-alpha03'
appCompat = '1.7.0-alpha01'
archCore = '2.2.0-alpha01'
browser = '1.4.0'
constraintLayout = '2.1.4'
core = '1.10.0-alpha01'
drawerLayout = '1.2.0-alpha01'
exifInterface = '1.3.5'
fragment = '1.6.0-alpha04'
lifecycle = '2.6.0-alpha04'
multidex = '2.0.1'
navigation = '2.6.0-alpha04'
paging = '3.2.0-alpha03'
preference = '1.2.0'
recyclerView = '1.3.0-rc01'
room = '2.5.0'
swipeRefreshLayout = '1.1.0'
viewPager2 = '1.1.0-beta01'
wearable = '2.8.1'
wear = '1.2.0'
wearWatchFaceComplication = '1.1.1'
workManager = '2.8.0-rc01'

# Firebase
firebaseAnalytics = '21.2.0'
firebaseCrashlytics = '18.3.3'
firebaseCrashlyticsGradle = '2.9.2'
firebasePerf = '20.3.1'
firebasePerfPlugin = '1.4.2'
googleServices = '4.3.15'
playServicesWearable = '18.0.0'

# Jetbrains
coroutines = '1.6.4'
dokka = '1.6.0'
kotlin = '1.7.20'
ksp = '1.7.20-1.0.8'

# Other
coil = '1.3.2'
material = '1.8.0-rc01'
okhttp = '3.12.12'
okhttpCoroutines = '1.0'
retrofit = '2.9.0'
subsampling = '3.10.0'
tasker = '0.4.1'

[libraries]

agp = { group = "com.android.tools.build", name="gradle", version.ref = "agp" }

# AndroidX
navigation-safeargs = { group = "androidx.navigation", name="navigation-safe-args-gradle-plugin", version.ref = "navigation" }

# Firebase
firebase-googleservices = { group = "com.google.gms", name="google-services", version.ref = "googleServices" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name="firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-perf-plugin = { group = "com.google.firebase", name="perf-plugin", version.ref = "firebasePerfPlugin" }

# Jetbrains
jetbrains-dokka = { group = "org.jetbrains.dokka", name="dokka-gradle-plugin", version.ref ="dokka" }
jetbrains-kotlin-plugin = { group = "org.jetbrains.kotlin", name="kotlin-gradle-plugin", version.ref ="kotlin" }

# Other